[book]
title = "Linux Under the Hood"
authors = ["Xiaofeng"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/henrywang/linux-under-the-hood"
edit-url-template = "https://github.com/henrywang/linux-under-the-hood/edit/main/{path}"
